# Eureka Configuration
config:
  name: eureka
  version: 1.0.0
  connectivity_mask: 2
  sampling_rate: 44100
  fft_window_size: 4096
  overlap_ratio: 0.75
  fan_value: 15
  amplitude_min: 10
  peak_neighborhood_size: 3
  min_hash_time_delta: 0
  max_hash_time_delta: 2000
  peak_sort: true
  fingerprint_reduction: 20
  fingerprint_limit: 0

recognition:
  top_results: 2

database:
  type: mysql
  user: mysql
  password: password
  db_name: eureka
  host: localhost
  port: 3306
  params: "parseTime=true&charset=utf8mb4"

tables:
  songs:
    name: songs
    fields:
      id: song_id
      name: song_name
      artist: artist
      fingerprinted: fingerprinted
      file_sha1: file_sha1
      total_hashes: total_hashes
  fingerprints:
    name: fingerprints
    fields:
      hash: hash
      offset: offset
